// src/ui/Header.svelte
<script lang="ts">
  import { home } from "../ha/store.svelte";
  import { watchEntities } from "../ha/subscriptions.svelte";
  import { language, t } from "../i18n/index.svelte";
  import { weatherEntityId } from "../model/model.svelte";
  import { formatNumber } from "./format";
  import Icon from "./Icon.svelte";
  import { entityIcon } from "./icons";
  import SettingsMenu from "./SettingsMenu.svelte";

  /** Big clock, date and outside weather: readable from across the room. */

  let now = $state(new Date());
  $effect(() => {
    const id = setInterval(() => (now = new Date()), 10_000);
    return () => clearInterval(id);
  });

  function greetingKey(hour: number) {
    if (hour < 5) return "home.greeting_night";
    if (hour < 12) return "home.greeting_morning";
    if (hour < 18) return "home.greeting_afternoon";
    if (hour < 23) return "home.greeting_evening";
    return "home.greeting_night";
  }

  const timeFormat = $derived(new Intl.DateTimeFormat(language(), { hour: "2-digit", minute: "2-digit", hourCycle: "h23" }));
  const dateFormat = $derived(new Intl.DateTimeFormat(language(), { weekday: "long", day: "numeric", month: "long" }));
  const weatherId = $derived(weatherEntityId());
  watchEntities(() => [weatherId]);
  const weather = $derived(home.entity(weatherId));
</script>

<header class="header">
  <div>
    <div class="clock">{timeFormat.format(now)}</div>
    <div class="header-sub">
      {t(greetingKey(now.getHours()))} · {dateFormat.format(now)}
    </div>
  </div>
  <div class="header-side">
    {#if weather && weather.attributes.temperature != null}
      <div class="weather">
        <Icon path={entityIcon(weather)} size={32} />
        <strong>{formatNumber(weather.attributes.temperature)}°</strong>
      </div>
    {/if}
    <SettingsMenu />
  </div>
</header>

// src/ui/Header.tsx
import { useEffect, useState } from "react";
import { useTranslation } from "react-i18next";
import { useHome } from "../ha/store";
import type { Language } from "../i18n";
import { formatNumber } from "./format";
import { Icon, entityIcon } from "./Icon";
import { SettingsMenu } from "./SettingsMenu";

function useNow(intervalMs = 10_000) {
  const [now, setNow] = useState(() => new Date());
  useEffect(() => {
    const id = setInterval(() => setNow(new Date()), intervalMs);
    return () => clearInterval(id);
  }, [intervalMs]);
  return now;
}

function greetingKey(hour: number) {
  if (hour < 5) return "home.greeting_night";
  if (hour < 12) return "home.greeting_morning";
  if (hour < 18) return "home.greeting_afternoon";
  if (hour < 23) return "home.greeting_evening";
  return "home.greeting_night";
}

/** Big clock, date and outside weather: readable from across the room. */
export function Header() {
  const { t, i18n } = useTranslation();
  const now = useNow();
  const weather = useHome((s) => Object.values(s.entities).find((e) => e.entity_id.startsWith("weather.")));
  const lang = i18n.language as Language;

  const time = new Intl.DateTimeFormat(lang, { hour: "2-digit", minute: "2-digit", hourCycle: "h23" }).format(now);
  const date = new Intl.DateTimeFormat(lang, { weekday: "long", day: "numeric", month: "long" }).format(now);

  return (
    <header className="header">
      <div>
        <div className="clock">{time}</div>
        <div className="header-sub">
          {t(greetingKey(now.getHours()))} · {date}
        </div>
      </div>
      <div className="header-side">
        {weather && weather.attributes.temperature != null && (
          <div className="weather">
            <Icon path={entityIcon(weather)} size={32} />
            <strong>{formatNumber(weather.attributes.temperature)}°</strong>
          </div>
        )}
        <SettingsMenu />
      </div>
    </header>
  );
}
