// src/screens/RoomScreen.tsx
import { mdiChevronLeft } from "@mdi/js";
import type { ReactNode } from "react";
import { useTranslation } from "react-i18next";
import { callService, useHome } from "../ha/store";
import { useRoom } from "../model/home";
import { formatHumidity, formatTemperature } from "../ui/format";
import { Icon } from "../ui/Icon";
import { ClimateTile, SensorTile, ToggleTile } from "../ui/tiles";
import { navigate } from "../router";

export function RoomScreen({ areaId }: { areaId: string }) {
  const { t } = useTranslation();
  const room = useRoom(areaId);
  const temperature = useHome((s) => (room?.temperature ? s.entities[room.temperature] : undefined));
  const humidity = useHome((s) => (room?.humidity ? s.entities[room.humidity] : undefined));
  const lightsOn = useHome((s) => room?.lights.some((id) => s.entities[id]?.state === "on") ?? false);

  if (!room) return <div className="center">{t("app.connecting")}</div>;
  const { area } = room;
  const empty = [room.lights, room.climate, room.switches, room.media, room.sensors].every((l) => l.length === 0);

  return (
    <main className="screen">
      <header className="room-header">
        <button className="round-btn" aria-label={t("room.back")} onClick={() => navigate("/")}>
          <Icon path={mdiChevronLeft} size={28} />
        </button>
        <h1>{area.name}</h1>
        <div className="room-climate">
          {temperature && <span>{formatTemperature(temperature)}</span>}
          {humidity && <span>{formatHumidity(humidity)}</span>}
        </div>
      </header>

      {empty && <p className="empty">{t("room.empty")}</p>}

      <Section
        title={t("room.lights")}
        ids={room.lights}
        action={
          room.lights.length > 1 && (
            <button
              className="chip"
              onClick={() => void callService("homeassistant", lightsOn ? "turn_off" : "turn_on", {}, { entity_id: room.lights })}
            >
              {lightsOn ? t("room.allOff") : t("room.allOn")}
            </button>
          )
        }
      >
        {room.lights.map((id) => <ToggleTile key={id} entityId={id} area={area} />)}
      </Section>
      <Section title={t("room.climate")} ids={room.climate}>
        {room.climate.map((id) => <ClimateTile key={id} entityId={id} area={area} />)}
      </Section>
      <Section title={t("room.switches")} ids={room.switches}>
        {room.switches.map((id) => <ToggleTile key={id} entityId={id} area={area} />)}
      </Section>
      <Section title={t("room.media")} ids={room.media}>
        {room.media.map((id) => <SensorTile key={id} entityId={id} area={area} />)}
      </Section>
      <Section title={t("room.sensors")} ids={room.sensors}>
        {room.sensors.map((id) => <SensorTile key={id} entityId={id} area={area} />)}
      </Section>
    </main>
  );
}

function Section({ title, ids, action, children }: { title: string; ids: string[]; action?: ReactNode; children: ReactNode }) {
  if (ids.length === 0) return null;
  return (
    <section className="section">
      <div className="section-head">
        <h2>{title}</h2>
        {action}
      </div>
      <div className="grid">{children}</div>
    </section>
  );
}

// src/screens/RoomScreen.svelte
<script lang="ts">
  import { mdiChevronLeft } from "@mdi/js";
  import type { Snippet } from "svelte";
  import { callService, home } from "../ha/store.svelte";
  import { watchEntities } from "../ha/subscriptions.svelte";
  import { t } from "../i18n/index.svelte";
  import { findRoom } from "../model/model.svelte";
  import { navigate } from "../router.svelte";
  import ClimateTile from "../ui/ClimateTile.svelte";
  import { formatHumidity, formatTemperature } from "../ui/format";
  import Icon from "../ui/Icon.svelte";
  import SensorTile from "../ui/SensorTile.svelte";
  import ToggleTile from "../ui/ToggleTile.svelte";

  let { areaId }: { areaId: string } = $props();

  const room = $derived(findRoom(areaId));
  watchEntities(() => [room?.temperature, room?.humidity, ...(room?.lights ?? [])]);
  const temperature = $derived(home.entity(room?.temperature));
  const humidity = $derived(home.entity(room?.humidity));
  const lightsOn = $derived(room?.lights.some((id) => home.entity(id)?.state === "on") ?? false);
  const empty = $derived(
    !!room && [room.lights, room.climate, room.switches, room.media, room.sensors].every((l) => l.length === 0),
  );

  function toggleAll() {
    if (room) void callService("homeassistant", lightsOn ? "turn_off" : "turn_on", {}, { entity_id: room.lights });
  }
</script>

{#snippet section(title: string, ids: string[], tile: Snippet<[string]>, action?: Snippet)}
  {#if ids.length > 0}
    <section class="section">
      <div class="section-head">
        <h2>{title}</h2>
        {@render action?.()}
      </div>
      <div class="grid">
        {#each ids as id (id)}
          {@render tile(id)}
        {/each}
      </div>
    </section>
  {/if}
{/snippet}

{#if !room}
  <div class="center">{t("app.connecting")}</div>
{:else}
  {@const area = room.area}

  {#snippet toggle(id: string)}<ToggleTile entityId={id} {area} />{/snippet}
  {#snippet climate(id: string)}<ClimateTile entityId={id} {area} />{/snippet}
  {#snippet sensor(id: string)}<SensorTile entityId={id} {area} />{/snippet}
  {#snippet allLights()}
    {#if room.lights.length > 1}
      <button class="chip" onclick={toggleAll}>{lightsOn ? t("room.allOff") : t("room.allOn")}</button>
    {/if}
  {/snippet}

  <main class="screen">
    <header class="room-header">
      <button class="round-btn" aria-label={t("room.back")} onclick={() => navigate("/")}>
        <Icon path={mdiChevronLeft} size={28} />
      </button>
      <h1>{area.name}</h1>
      <div class="room-climate">
        {#if temperature}<span>{formatTemperature(temperature)}</span>{/if}
        {#if humidity}<span>{formatHumidity(humidity)}</span>{/if}
      </div>
    </header>

    {#if empty}<p class="empty">{t("room.empty")}</p>{/if}

    {@render section(t("room.lights"), room.lights, toggle, allLights)}
    {@render section(t("room.climate"), room.climate, climate)}
    {@render section(t("room.switches"), room.switches, toggle)}
    {@render section(t("room.media"), room.media, sensor)}
    {@render section(t("room.sensors"), room.sensors, sensor)}
  </main>
{/if}
